### ISSUE TITLE
Sparse factors

### ISSUE THREAD

**Issue by davidweichiang** [diprism/fggs#164]
- [ ] extend JSON format (but main simple output should probably still return (list-of-)*numbers)
- [ ] make sum-product work on EmbeddedTensor
  - main simple sum_product function should probably still return Tensor
  - forward & backward should stick nonphysical into [ctx](https://pytorch.org/docs/stable/notes/extending.html#extending-autograd), oh well

**Comment by ccshan** [comment]
`getEqWeights` makes a non-sparse tensor... Maybe PERPL should provide a "fail unless equal" construct.
